### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by JanRuettinger** [riverqueue/river#127]
Hi,

in the [docs](https://riverqueue.com) close to the bottom there is a really nice UI which shows the state of all jobs. 

Is the code for that UI public as well?
If yes, how I access it?

Picture of the UI:

![web-dashboard-preview 461dc852](https://github.com/riverqueue/river/assets/8582703/56e5f6de-32e7-4106-923d-b18b75cd08ba)

Happy holidays!

**Comment by brandur** [comment]
Hi @JanRuettinger, it's not public yet. We're working on it and @bgentry's got an early prototype which is where the screenshots come from, but it needs more work. (A very rough estimate, but) I'd cautiously slate it for release something like Q2/Q3 2024.

**Comment by bgentry** [comment]
I’m definitely trying to beat that timeline 😉 but yeah it is not quite ready yet. I hope to share more on it soon @JanRuettinger. We can leave this issue open meanwhile since this is something we are committed to shipping.

**Comment by safaci2000** [comment]
I would be very curious to see any updates on this even if it's beta / alpha versions.

**Comment by noahjamison** [comment]
Hey @bgentry and @brandur, I just starting using River and I'm a huge fan. You've clearly put a lot of work into this project and it's a joy to use. Props to you both!

One thing that would greatly improve the DX is a frontend, which I see you're working on. I'm using River for a project and would love to see a UI sooner rather than later, are you open to contributions? If you're writing it in React/Next or htmx I'd love to help out. Or If you'd rather keep it internal, I understand that too.

**Comment by brandur** [comment]
Thanks @noahjamison! And for your offer of help. We're probably going to keep this an internal thing for now as the first release of the UI may be optimizing a little for functionality over perfect code quality, but we appreciate the offer.

We haven't bumped this thread in a while, but I know @bgentry's been working on this pretty constantly since the last update. It's a large chunk of work, but it's definitely coming. Still can't commit to an exact schedule, but I'd expect something in the next few months.

**Comment by noahjamison** [comment]
Sounds good, thanks for letting me know! Good luck with it, can't wait to see what you come up with.

**Comment by bgentry** [comment]
@noahjamison it's really getting close now. I'm just about there on implementing the initial set of functionality in the UI (see #301) and then there's a bit of work to do around the packaging/distribution/deployment side of things for the Go API + React TS / Vite frontend. I hope to have an early version of this ready to share in the next few weeks so stay tuned 🤞

Of course there will be more to do to make it truly great (more robust, scalable, feature-rich, etc), but one step at a time :shipit: 

Meanwhile, if anybody has any info they want to add on what specifically they want the UI to _do_ or how you're hoping to use it, please feel free to share.

**Comment by umed** [comment]
Hi guys,

First of you've done tremendous work. Greatly appreciate it!
 
I'm too waiting for that Web UI though.

> Meanwhile, if anybody has any info they want to add on what specifically they want the UI to _do_ or how you're hoping to use it, please feel free to share.

It would be nice if we don't have to deploy Web UI per database. So, we could just connect single instance to multiple databases simultaneously and, maybe, have a dashboard per database or just property to differentiate jobs in different databases.

Thanks a lot for great work!

**Comment by doron-cohen** [comment]
Hi, We too will be happy to get a beta if there will be any.

**Comment by bgentry** [comment]
🔜 😄
