### ISSUE TITLE
Is elector namespace unnecessary?

### ISSUE THREAD

**Issue by bgentry** [riverqueue/river#128]
I came across this section while working on something else today:

https://github.com/riverqueue/river/blob/6771fd3498118105cb0dff3ce7eead90d74924eb/client.go#L446-L449

This `instanceName` variable is only used in the subsequent initialization of the leader election routine. I think the original intention here was that if we had a config for which Postgres schema to use, that the leader election would need to be scoped to that particular schema. But given how our support for multiple schemas evolved as available by default accidentally (merely due to them being configurable in the pgx config) I'm not sure if this is actually needed at all anymore. Won't the elector inherit the schema from the pgx pool config, and thus automatically be acting on the correct schema with no additional configuration?

Should we just remove the variable altogether @brandur?

**Comment by brandur** [comment]
Hm, good question.

Reading the LISTEN/NOTIFY docs, I think that that channels are scoped to the current database (rather than current schema), so the one case where we might need something like this is if you were trying to run two separate River instances in the same database on different schemas. Leadership and job notification would share channels, and the wrong thing might happen.

That said I don't think that works right now anyway, so `instanceName` isn't really doing anything for us as far as I can tell. My vote is to remove it until we've better demonstrated that we need it for something.

**Comment by brandur** [comment]
Ended up moving the instance name into the elector in #281 given it's not really used and we don't have plans to use it. I suspect you're right here in that we probably don't need it because even multiple installations in one DB will just use alternate schema names instead.

**Comment by bgentry** [comment]
Resolved by #325.
