### ISSUE TITLE
Separate worker and insertion of jobs.

### ISSUE THREAD

**Issue by brycegoh** [riverqueue/river#131]
Hello! Have been playing around with River and wanted to ask if it's possible to have a client without workers just for insertion of jobs so that we are able to have workers on a separate machine from the main server.

Thanks!

**Comment by brandur** [comment]
@brycegoh Yeah, it's a bit hard to find, but the docs for this are in the [`Config` section](https://pkg.go.dev/github.com/riverqueue/river#Config):

```
	// Queues is a list of queue names for this client to operate on along with
	// configuration for the queue like the maximum number of workers to run for
	// each queue.
	//
	// This field may be omitted for a program that's only queueing jobs rather
	// than working them. If it's specified, then Workers must also be given.
	Queues map[[string](https://pkg.go.dev/builtin#string)][QueueConfig](https://pkg.go.dev/github.com/riverqueue/river#QueueConfig)
```

So omitting the `Queues` configuration property makes the client insert only. You can technically omit the `Workers` property as well (where jobs are configured), but we recommend leaving this in because if it's present, the River client will verify at insertion that a job is properly registered with a corresponding worker that can process it.
