### ISSUE TITLE
river hides panic stack traces in database

### ISSUE THREAD

**Issue by elee1766** [riverqueue/river#418]
often in development, someone will write a worker that panics. 

currently, the stack is uploaded to the database, and the stack trace is not printed in the log
https://github.com/riverqueue/river/blob/master/job_executor.go#L169-L183

this is very annoying in development, because now the developer needs to query the database to get the stack trace, and it's rather hard to actually get nice formatted traces. it makes debugging and development much slower overall. 

i saw there was https://github.com/riverqueue/river/issues/122 . some sort of middleware like `func(next func(context.Context) error) func(context.Context) error` could maybe help with both these problems

**Comment by bgentry** [comment]
Hi @elee1766, have you added a panic handler? In addition to reporting to a bug tracking service, you could customize it to print the trace in dev. https://riverqueue.com/docs/error-handling

**Comment by elee1766** [comment]
the stack trace is polluted at the panichandler, I couldn't find a way to get the stack trace from the result object since only the error is passed.

we could implement and hook a custom panic handler to the job processing function, but it just seems silly to change the semantics of a workers job when I want to change how the job executor executes jobs regardless of the underlying work to be done.

**Comment by bgentry** [comment]
Looking at this in the executor @brandur, I'm seeing that we do actually capture trace correctly with `debug.Stack()` _within_ the recover, which is what we record to the database. However we the don't actually expose this to the panic handler, only the raw panic value, which seems like an important oversight.

I think it's essential that this be available in some way. Since we already have the API for panic handling, our options are (1) break the API by adding the trace as another arg to `ErrorHandler.HandlePanic()`, or (2) stuff it in the context to avoid breaking the API. I lean pretty strongly toward (1) in this case because the trace is pretty important for panics IMO, thoughts?

**Comment by brandur** [comment]
Yeah, no way we do it via context shenanigans. Also +1 on the API breakage — I think we can get away with it given this is a feature most users aren't going to be dipping into yet (hopefully), and it's reasonably easy for them to fix.

I'll take this.

**Comment by bgentry** [comment]
@elee1766 the `HandlePanic` method now passes the original stack trace as an arg as of #423 / v0.9.0. Can you let us know if this makes it trivial for you to print your trace in dev?

**Comment by elee1766** [comment]
@bgentry yep, its good now.
![image](https://github.com/riverqueue/river/assets/2260857/ae1aebe2-00f2-4b53-9807-8a271cbeca16)
