### ISSUE TITLE
Minimum Postgres version requirement?

### ISSUE THREAD

**Issue by linux2647** [riverqueue/river#49]
What is the minimum version of Postgres required to run river?  From my poking around, I would guess Postgres 12 because the Reindexer uses the [`CONCURRENTLY` option](https://github.com/riverqueue/river/blob/fa94b350c15a151f1dafe507b900d09e608db197/internal/maintenance/reindexer.go#L149)?

**Comment by bgentry** [comment]
I opened https://github.com/riverqueue/river/pull/50 to validate that River's main test suite works against the most recent 3 major Postgres versions. I don't imagine we'll want to test further back than that, at least not for every CI run and during this initial beta. Are you using an older version?

The reindexer is actually not enabled currently anyway because we wanted to make sure we spent more time getting the design and defaults correct with it.

**Comment by bgentry** [comment]
I'm closing the issue for now as #50 is merged, but please feel free to chime back in. Thanks :v:

**Comment by linux2647** [comment]
At my work, we're running PG 12 and 13 (and maybe an 11 somewhere?—hopefully not).  Upgrading major versions of Postgres isn't the most pleasant operation, so it's often not done.  That said, you supporting the last three major versions of Postgres seems reasonable.  We can internally run our own checks to make sure that River still works with our older databases.  Maybe the allure of a transaction job queue might be strong enough to get some of these databases upgraded 😛

BTW, thank you so much for writing this library.  My colleagues and I at work have been craving something like this and we've been considering writing something ourselves.  Now it seems we won't have too.

**Comment by linux2647** [comment]
We have one service using River that's on Postgres 13.  It's also deployed to a test environment running Postgres 12.  I'm not sure how extensive it's been tested in the PG12 environment (that test environment doesn't get a lot of activity) but it seems to be doing fine.  In production, I can't say that we've used every feature of River, but it's done great handling a workload of around 800k jobs/day, or about 10/sec
