### ISSUE TITLE
Job uniqueness semantic

### ISSUE THREAD

**Issue by fsaintjacques** [riverqueue/river#62]
After reading the documentation multiple times, it's still unclear wether unique jobs can run simultaneously. I will explain my scenario. I want a system where I have unique jobs which must run at most once concurrently (the job can retry, but they cannot run in parallel). I also want to be able to enqueue the same unique Job at most once. In other words, I'd like to enqueue a unique job, and if it's currently running, enqueue another one. If there's already one running and one queued with the same key, do nothing.

It seems that this could be achieved by using `UniqueOpts` with a caller defined key and a custom `ByState: ...`. But my challenge is understanding how workers can still pickup the newly enqueued job if there's already a worker executing the currently running job with the same key.

If I understand correctly, the uniqueness is only checked at insertion, thus with the previous scenario, I could still have 2 concurrent workers on the same unique job.

**Comment by bgentry** [comment]
Hi @fsaintjacques, you are correct that uniqueness is a guarantee at insertion time based on the unique opts. It’s conceivably possible that two such jobs could be running at the same time if they were inserted with different params and if one was retrying.

In order to ensure that only one of them is running at a time you may need to look at using an advisory lock or some other mechanism to guarantee it. In the future we hope to provide mechanisms to ensure one-at-a-time execution for specific jobs as desired.

**Comment by bgentry** [comment]
@brandur I’m not certain of the best way to improve the docs to make this clearer but I imagine we can do something to improve it. Thoughts?

**Comment by bgentry** [comment]
I think that’s a solid improvement for now. Please let us know if you have other ideas for things here that could be explained more clearly @fsaintjacques ✌️
