### ISSUE TITLE
Unique jobs taking completed job into account by default

### ISSUE THREAD

**Issue by gaffneyc** [riverqueue/river#677]
We have a PeriodicJob that runs every minute but we allow it to take up to 3 minutes and we only want one job running at a time. We had it set up as below and were surprised to see that it was taking completed jobs into account by default. This meant that 2 out of every 3 job weren't scheduled because there was an existing completed job within the uniqueness window. The fix was to specify `ByState` without the completed state which was clear when reading the ByState documentation.

I think the default behavior is surprising and I would opt to exclude completed jobs by default. It's also possible that it's well documented but I missed it somewhere.

```go
type JobArgs struct {}
type Job struct {}

func (JobArgs) InsertOpts() river.InsertOpts {
  return river.InsertOpts{
    MaxAttempts: 1,
    UniqueOpts: river.UniqueOpts {
      ByPeriod: 3 * time.Minute,
    }
  }
}

func (Job) Timeout(*river.Job[JobArgs]) time.Duration {
  return 3 * time.Minutes
}

func PeriodicJobs() []*river.PeriodicJob {
  job := func(job river.JobArgs) func() (river.JobArgs, *river.InsertOpts) {
    return func() (river.JobArgs, *river.InsertOpts) {
      return job, nil
    }
  }

  return []*river.PeriodicJob{
    river.NewPeriodicJob(cron.MustParse("* * * * *", job(&JobArgs{}), nil),
  }
}
```

**Comment by bgentry** [comment]
Hi @gaffneyc, I think this is documented reasonably well in [the doc site](https://riverqueue.com/docs/unique-jobs#unique-by-state) and [the Go docs](https://pkg.go.dev/github.com/riverqueue/river#UniqueOpts). I'm afraid that IMO it would be more surprising if the default was that a unique job was allowed to be duplicated when that specific job had already been executed. For example, common use cases are to run a given job once per time interval, or to ensure that i.e. a job to deliver a specific email can only execute one time—both of these are cases where the default makes the most sense.

I think for now it's best to leave this as-is, especially since changing it would be another breaking change. But if you see anywhere you think this is explained poorly or not at all, please let me know so I can try to improve those!

**Comment by gaffneyc** [comment]
@bgentry Thanks, I missed that documentation and I agree it makes sense. It might be that it's only documented in the `ByState` section which I glossed over as I didn't think it applied for this job. It may be worth calling out the default in the examples [under unique properties](https://riverqueue.com/docs/unique-jobs#unique-properties).
